ROFI_CONFIG_LOCATION=$HOME/.config/rofi
ROFI_TOOL_LOCATION=$HOME/.lazyTools.d/rofi
ROFI_THEME_FILE="rofi-theme"
ROFI_CONFIG_FILE="rofi-conf"

## Copy config
cp $ROFI_TOOL_LOCATION/$ROFI_THEME_FILE $ROFI_CONFIG_LOCATION/nord.rasi
cp $ROFI_TOOL_LOCATION/$ROFI_CONFIG_FILE $ROFI_CONFIG_LOCATION/config
