ROFI_CONFIG_LOCATION=$HOME/.config/rofi
ROFI_TOOL_LOCATION=$HOME/.lazyTools.d/rofi
ROFI_THEME_DRACULA_FILE="rofi-theme-dracula"
ROFI_THEME_NORD_FILE="rofi-theme-nord"
ROFI_CONFIG_FILE="rofi-config"

## Copy config
ln -s $ROFI_TOOL_LOCATION/$ROFI_THEME_NORD_FILE $ROFI_CONFIG_LOCATION/nord.rasi
ln -s $ROFI_TOOL_LOCATION/$ROFI_THEME_DRACULA_FILE $ROFI_CONFIG_LOCATION/dracula.rasi
ln -s $ROFI_TOOL_LOCATION/$ROFI_CONFIG_FILE $ROFI_CONFIG_LOCATION/config
